# Railway için Çoklu Hizmet Yapılandırması
# Bu dosya, aynı depodan iki farklı hizmetin nasıl oluşturulacağını tanımlar.

# 1. Keycloak Hizmeti (Dockerfile ile)
[[services]]
name = "keycloak"
builder = "dockerfile"
dockerfilePath = "Keycloak.Dockerfile"

# 2. Backend Hizmeti (Nixpacks ile)
[[services]]
name = "backend"
builder = "nixpacks"
startCommand = "npm run start:prod" 