[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/api/health"
healthcheckTimeout = 600

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
KEYCLOAK_URL = "http://keycloack.railway.internal:8080"
KEYCLOAK_PUBLIC_URL = "https://keycloack-production.up.railway.app"
KEYCLOAK_ADMIN_USERNAME = "admin"
KEYCLOAK_ADMIN_PASSWORD = "SuperSecure123!"
KEYCLOAK_CLIENT_ID = "business-portal"
KEYCLOAK_CLIENT_SECRET = "lmv5iNnI0H1RyG4oyVCcCYJeqv3vahct"
KEYCLOAK_REALM = "business-portal"
JWT_SECRET = "your-super-secret-jwt-key-here-change-in-production"
JWT_EXPIRES_IN = "24h"
CORS_ORIGIN = "*"
CORS_CREDENTIALS = "true"

# Database Configuration - PostgreSQL Plugin Variables
DB_HOST = "${{Postgres.PGHOST}}"
DB_PORT = "${{Postgres.PGPORT}}"
DB_USERNAME = "${{Postgres.PGUSER}}"
DB_PASSWORD = "${{Postgres.PGPASSWORD}}"
DB_DATABASE = "${{Postgres.PGDATABASE}}"

# Application Settings
FRONTEND_URL = "https://frontend-production-0d2c.up.railway.app"
SUPER_ADMIN_EMAIL = "admin@nexus-portal.com"
SUPER_ADMIN_PASSWORD = "SuperAdmin123!"
SUPER_ADMIN_FIRST_NAME = "Super"
SUPER_ADMIN_LAST_NAME = "Admin"

# Encryption
ENCRYPTION_KEY = "your-32-character-encryption-key-here!"
ENCRYPTION_IV = "your-16-char-iv-here"

# Force deployment trigger
DEPLOYMENT_VERSION = "1.0.3"
TENANT_FIX_APPLIED = "true"
SSL_BYPASS_ENHANCED = "true" 