# Bu GitHub Actions iş akışı, Keycloak imajını oluşturur ve GitHub Container Registry'ye (ghcr.io) gönderir.
name: Build and Push Keycloak Image

on:
  # 'main' branch'ine her push yapıldığında bu iş akışı çalışır.
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Kodu Checkout Yap
        uses: actions/checkout@v4

      - name: GitHub Container Registry'ye Giriş Yap
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Imajını Build ve Push Et
        uses: docker/build-push-action@v5
        with:
          # 'context' artık reponun kök dizini olduğu için '.' olarak ayarlandı.
          context: .
          # Dockerfile yolu da kök dizine göre belirlendi.
          file: ./Keycloak.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/keycloak:latest 